name: Build and test
description: 'Build and run tests for a CMake project using latest tools'

inputs:
  dependencies:
    description: 'List of extra dependencies to install'
    default: ''
  clang_version:
    description: 'clang version to use (just the number or "main")'
    default: 'main'
  cmake_args:
    description: 'List of extra CMake arguments'
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      with:
        submodules: true
        path: repo

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail

        if [ "${{inputs.clang_version}}" = "main" ]; then
          suffix=""
        else
          suffix="-${{inputs.clang_version}}"
        fi

        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
          | gpg --dearmor \
          | sudo tee /usr/share/keyrings/llvm.gpg > /dev/null

        echo "deb [signed-by=/usr/share/keyrings/llvm.gpg] https://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)$suffix main" \
          | sudo tee /etc/apt/sources.list.d/llvm.list > /dev/null

        sudo apt-get update
        sudo apt-get install -y cmake ninja-build mold libstdc++-16-dev "clang$suffix" ${{inputs.dependencies}}

        clang_binary_version=$("clang++$suffix" -dumpversion | cut -d. -f1)
        echo "CLANG_BINARY_VERSION=$clang_binary_version" >> $GITHUB_ENV

        sudo apt-get install -y "clang-tools-$clang_binary_version"

    - name: Configure CMake
      shell: bash
      run: |
        cmake \
          -S "${{github.workspace}}/repo" \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Debug \
          -G"Ninja" \
          -DCMAKE_CXX_COMPILER="clang++-$CLANG_BINARY_VERSION" \
          -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS="clang-scan-deps-$CLANG_BINARY_VERSION" \
          -DCMAKE_CXX_FLAGS="-Og -fsanitize=address,undefined" \
          -DCMAKE_EXE_LINKER_FLAGS="-Wl,--fatal-warnings -fuse-ld=mold -fsanitize=address,undefined" \
          ${{inputs.cmake_args}}

    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        ctest --output-on-failure -j$(nproc)