name: Build and test

on:
  workflow_call:
    inputs:
      build_type:
        description: 'Debug or Release'
        default: 'Debug'
        type: string
      dependencies:
        description: 'List of extra dependencies to install'
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install clang dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libtinfo5 mold ${{inputs.dependencies}}

    - name: Install clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 18 all

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} -G"Ninja" -DCMAKE_CXX_COMPILER="clang++-18" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{inputs.build_type}} --output-on-failure
