name: Build and test

on:
  workflow_call:

env:
  build_type: ${{github.event.inputs.build_type || 'Debug'}}
  dependencies: ${{github.event.inputs.dependencies || ''}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install clang dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libtinfo5 mold ${{env.dependencies}}

    - name: Install clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh all

    - uses: lukka/get-cmake@latest
    
    - name: Pull dependencies
      run: git submodule update --init

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.build_type}} -G"Ninja" -DCMAKE_CXX_COMPILER="clang++-17" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.build_type}}
